language: node_js

node_js:
  - "node"  # Current - Latest features
  - "7"
  - "6"     # LTS - Recommended for most users
  - "5"

matrix:
  fast_finish: true

before_install:
  - npm install -g greenkeeper-lockfile@1

install:
  - npm install

before_script: greenkeeper-lockfile-update

script:
  - if [ "$TRAVIS_NODE_VERSION" == "node" ]; then npm run coverage:publish; fi
  - if [ "$TRAVIS_NODE_VERSION" != "node" ]; then npm run test; fi
  - npm run lint

after_script: greenkeeper-lockfile-upload
